server:
  host: 0.0.0.0
  port: 8080
  iot_port: 8443

database:
  postgres:
    host: app-postgres
    port: 5432
    user: rootstock
    password: rootstock
    dbname: rootstock
    sslmode: disable

identity:
  zitadel:
    host: zitadel
    port: 8080
    issuer: http://localhost:9999
    external_domain: localhost

authorization:
  opa:
    policy_path: /policies

observability:
  trace_exporter: otlp
  service_name: rootstock
  endpoint: otel-collector:4318
  enable_traces: true
  enable_metrics: true
  enable_logs: true

events:
  app_name: rootstock

cert:
  ca_cert_path: /certs/ca.crt
  ca_key_path: /certs/ca.key
  server_cert_path: /certs/server.crt
  server_key_path: /certs/server.key
  cert_lifetime_days: 90
